### ISSUE TITLE
png image compress

### ISSUE THREAD

**Issue by vinaykumar4848** [oukan/angular-image-compress#11]
Hi,
i tried to compress the png file its showing with background black in the image how can i show with transparency image @oukan @patelmayankce

**Comment by vinaykumar4848** [comment]
> Hi,
> i tried to compress the png file its showing with background black in the image how can i show with transparency image

**Comment by patelmayankce** [comment]
@vinaykumar4848 can you paste your code?

BTW, you have to pass the **resize-type** like below

`<input id="inputImage" type="file" accept="image/*" image="image1" resize-max-height="800" resize-max-width="800" resize-quality="0.7" resize-type="png" ng-image-compress />
`

**resize-type="png"**

**Comment by patelmayankce** [comment]
i have used in one of my project as below,

`<input class="inputfile" type="file" accept="image/*" image="vm.branding.logoImage" resize-max-width="300" resize-max-height="300" resize-quality="0.7" resize-type="png" ng-image-compress/>
`

**Comment by vinaykumar4848** [comment]
@patelmayankce if image size in MB taking too long time to display

**Comment by patelmayankce** [comment]
@vinaykumar4848 , i tried with [5MB](http://www.ucolick.org/~diemand/vl2/images/composite3.png) size PNG image and it loads in few sec.
