### ISSUE TITLE
Can I use in a controller?

### ISSUE THREAD

**Issue by imarem** [oukan/angular-image-compress#2]
Would it be possible to use this library in a controller, before upload the image to server?

Thanks!!!

**Comment by vedprakash15** [comment]
I'm using your code in my project. image is compressed successfully. But i'm not able to add this image in my controller.
my html code is-

<div class="form-group text-16px" style="margin-top: 20px !important;">
    <label>Choose Material Photo : </label>
    <div>
    <input id="materialImage" type="file" accept="image/*" image="image1" resize-max-height="800" resize-max-width="800" resize-quality="0.7" resize-type="image/jpg" file-model="file" name="materialImage" onChange="checkFile()" ng-image-compress/>
    <div id="choose-image-compresser">
      <div image="image1" result-image="myCompressedImage"></div>
      </div>
        <span id="image-size-error" style="color:red;" hidden=""><small>Image size is too large please upload upto 2MB image.</small></span>
    </div>
</div> 

and my js code is-(in controller)
console.log($scope.image1.compressed.dataURL);
                                var byteCharacters = atob($scope.image1.compressed.dataURL.replace(/^data:image\/(png|jpg);base64,/,''));
                                var byteNumbers = new Array(byteCharacters.length);
                                for (var i = 0; i < byteCharacters.length; i++) {
                                    byteNumbers[i] = byteCharacters
                                            .charCodeAt(i);
                                }
                                var byteArray = new Uint8Array(byteNumbers);
                                var blob = new Blob([ byteArray ], {
                                    type : undefined
                                });
____________________________________Error - message______________________________________________________
Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
--> how can i solved this error
