### ISSUE TITLE
Image resize in mm

### ISSUE THREAD

**Issue by jokerbt20** [oukan/angular-image-compress#3]
First of all ... GREAT JOB on angular-image-compress i like it a lot . But i have question , how can i adapt script to work with mm (for scaling A4 image format) ?

**Comment by oukan** [comment]
Canvas drawimage width only support px.
You can calculate cm to px.
if 96 DPI, 1 Inch = 96 Pixels , 1 CM = 1/2.54 Inch = 96/2.54 Pixels = 37.7953 Pixels
