### ISSUE TITLE
Unable to get compressed image for uploading in post API call

### ISSUE THREAD

**Issue by gaurav150493** [oukan/angular-image-compress#5]
This plugin is working perfect and i am getting compressed image but how to send that compressed image in post api call because the object i am getting contains only data-url of the compressed image.

Please help me with how to send this compressed image in post api call.

**Comment by oukan** [comment]
Always I upload base64 to server, but if you want to upload file to server, please view
https://stackoverflow.com/questions/6978156/get-base64-encode-file-data-from-input-form
